# Generated by Django 3.2.5 on 2022-08-25 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_downtime', models.TimeField(default=datetime.time(0, 30))),
                ('max_tasks', models.IntegerField(default=1)),
                ('qtasks_max_time', models.TimeField(default=datetime.time(2, 0))),
                ('problem_gone_delay', models.TimeField(default=datetime.time(1, 0))),
                ('problem_not_gone_delay', models.TimeField(default=datetime.time(23, 0))),
                ('recipients', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
