# Generated by Django 3.2.5 on 2022-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
