# Generated by Django 3.2.5 on 2022-09-02 06:22

from django.db import migrations, models
import django.db.models.deletion
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_sequence_instance'),
        ('bot', '0003_messageslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=2)),
                ('is_solved', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(default=shared.models.Instance.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='shared.instance')),
            ],
        ),
        migrations.DeleteModel(
            name='MessagesLog',
        ),
    ]
