# Generated by Django 3.2.5 on 2022-09-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_sequence_instance'),
        ('bot', '0004_auto_20220902_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueslog',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.instance'),
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.instance')),
            ],
        ),
    ]
