# Generated by Django 3.2.5 on 2022-09-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20220914_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotSettings',
        ),
    ]
